# Generated by Django 4.0.7 on 2022-08-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0008_user_phone_number_alter_user_full_name'),
        ('common', '0003_questionanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseclass',
            name='user',
        ),
        migrations.AddField(
            model_name='baseclass',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cooperations', to='tgbot.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='tgbot.user'),
            preserve_default=False,
        ),
    ]
