# Generated by Django 4.0.7 on 2022-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='group_msg_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
