# Generated by Django 4.0.7 on 2022-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_rm_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(default='uz', max_length=8),
            preserve_default=False,
        ),
    ]
