# Generated by Django 4.0.7 on 2022-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_alter_user_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(default='uz', max_length=8),
            preserve_default=False,
        ),
    ]
