# Generated by Django 4.0.7 on 2022-08-20 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0005_user_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='language_code',
        ),
    ]
