# Generated by Django 4.0.7 on 2022-08-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0006_remove_user_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
