# Generated by Django 4.0.7 on 2022-10-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_result_title_ru_result_title_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='categories.question'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='title_uz',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='condition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='categories.condition'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title_uz',
            field=models.TextField(null=True),
        ),
    ]
