# Generated by Django 4.0.7 on 2022-10-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_answer_question_alter_answer_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='score',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='categories.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='condition',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='categories.condition'),
        ),
    ]
