# Generated by Django 4.0.7 on 2022-08-22 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_answer_title_r_answer_title_u_category_title_r_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title_r',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='title_r',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='title_r',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title_r',
            new_name='title_ru',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='title_u',
        ),
        migrations.RemoveField(
            model_name='category',
            name='title_u',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='title_u',
        ),
        migrations.RemoveField(
            model_name='question',
            name='title_u',
        ),
    ]
