# Generated by Django 4.0.7 on 2022-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_rename_title_r_answer_title_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='condition',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='title_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
