# Generated by Django 4.0.7 on 2022-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0006_answer_title_uz_category_title_uz_condition_title_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
