# Generated by Django 4.0.7 on 2022-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ismi')),
                ('first_name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ismi')),
                ('first_name_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ismi')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Familiyasi')),
                ('last_name_ru', models.CharField(blank=True, max_length=256, null=True, verbose_name='Familiyasi')),
                ('last_name_uz', models.CharField(blank=True, max_length=256, null=True, verbose_name='Familiyasi')),
                ('content', models.TextField(blank=True, max_length=2048, null=True, verbose_name="Ma'lumot")),
                ('content_ru', models.TextField(blank=True, max_length=2048, null=True, verbose_name="Ma'lumot")),
                ('content_uz', models.TextField(blank=True, max_length=2048, null=True, verbose_name="Ma'lumot")),
                ('gender', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=256, null=True, verbose_name='Jinsi')),
                ('gender_ru', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=256, null=True, verbose_name='Jinsi')),
                ('gender_uz', models.CharField(blank=True, choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol'), ('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=256, null=True, verbose_name='Jinsi')),
                ('youtube', models.CharField(blank=True, max_length=256, null=True)),
                ('youtube_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('youtube_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('telegram', models.CharField(blank=True, max_length=256, null=True)),
                ('telegram_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('telegram_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('instagram_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('twitter_uz', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook_ru', models.CharField(blank=True, max_length=256, null=True)),
                ('facebook_uz', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
