# Generated by Django 4.0.7 on 2022-08-23 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Erkak', 'Erkak'), ('Ayol', 'Ayol')], default=1, max_length=256, verbose_name='Jinsi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='content',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name="Ma'lumot"),
        ),
    ]
