# Generated by Django 4.0.7 on 2022-08-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_doctor_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='content_ru',
            field=models.TextField(blank=True, max_length=2048, null=True, verbose_name='Информация'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='first_name_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='gender_ru',
            field=models.CharField(blank=True, choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=256, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='last_name_ru',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия'),
        ),
    ]
