# Generated by Django 4.0.7 on 2022-08-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_doctor_content_ru_doctor_first_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='facebook_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='instagram_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='telegram_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='twitter_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='youtube_ru',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
